---
- hosts: all
  tasks:
  - name: create cluster
    ansible.builtin.command: k3d cluster create local-k8s
    args:
      creates: ~/.kube/config
  - name: Install kubernetes python package
    ansible.builtin.pip:
      name: kubernetes

  - name: create admin user
    kubernetes.core.k8s:
      state: present
      src: ./kube/admin-user.yml
  - name: Add demo chart repo
    kubernetes.core.helm_repository:
      name: open-telemetry
      repo_url: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  - name: Deploy latest version of Opentelemetry demo
    kubernetes.core.helm:
      name: my-otel-demo
      chart_ref: open-telemetry/opentelemetry-demo
      release_namespace: default


