---
- hosts: all
  tasks:
  - name: create cluster
    ansible.builtin.command: k3d cluster create local-k8s
    args:
      creates: ~/.kube/config
  - name: Install kubernetes python package
    ansible.builtin.pip:
      name: kubernetes

  - name: create admin user
    kubernetes.core.k8s:
      state: present
      src: ./kube/admin-user.yml
  - name: Add dashboard chart repo
    kubernetes.core.helm_repository:
      name: kubernetes-dashboard
      repo_url: "https://kubernetes.github.io/dashboard"
  - name: Deploy latest version of Kubernetes dashboard
    kubernetes.core.helm:
      name: dashboard
      chart_ref: kubernetes-dashboard/kubernetes-dashboard
      release_namespace: default


